#include "cpu.hpp"
#include "arith.hpp"
#include "bin.hpp"
#include "decoder.hpp"
#include "stuff.hpp"
// #include "test.hpp"
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

u32 Cpu::exec(u32 word) {
  cur = word;
 // printf("%x ", word);
  Instr instr = Decoder::decodeA(word);
  switch (instr) {
  case Instr::adcImm:
    return adcImm();
  case Instr::adcReg:
    return adcReg();
  case Instr::adcShiftedReg:
    return adcShiftedReg();
  case Instr::sbcImm:
    return sbcImm();
  case Instr::sbcReg:
    return sbcReg();
  case Instr::sbcShiftedReg:
    return sbcShiftedReg();
  case Instr::addImm:
    return addImm();
  case Instr::addReg:
    return addReg();
  case Instr::addShiftedReg:
    return addShiftedReg();
  case Instr::subImm:
    return subImm();
  case Instr::subReg:
    return subReg();
  case Instr::subShiftedReg:
    return subShiftedReg();
  case Instr::cmnImm:
    return cmnImm();
  case Instr::cmnReg:
    return cmnReg();
  case Instr::cmnShiftedReg:
    return cmnShiftedReg();
  case Instr::cmpImm:
    return cmpImm();
  case Instr::cmpReg:
    return cmpReg();
  case Instr::cmpShiftedReg:
    return cmpShiftedReg();
  case Instr::adr: // not
    return adr();
  case Instr::andImm:
    return andImm();
  case Instr::andReg:
    return andReg();
  case Instr::andShiftedReg:
    return andShiftedReg();
  case Instr::orrReg:
    return orrReg();
  case Instr::lsrReg:
    return lsrReg();
  case Instr::orrShiftedReg:
    return orrShiftedReg();
  case Instr::eorImm:
    return eorImm();
  case Instr::eorReg:
    return eorReg();
  case Instr::eorShiftedReg:
    return eorShiftedReg();
  case Instr::teqImm:
    return teqImm();
  case Instr::teqReg:
    return teqReg();
  case Instr::teqShiftedReg:
    return teqShiftedReg();
  case Instr::tstImm:
    return tstImm();
  case Instr::tstReg:
    return tstReg();
  case Instr::tstShiftedReg:
    return tstShiftedReg();
  case Instr::asrImm:
    return asrImm();
  case Instr::asrReg:
    return asrReg();
  case Instr::lslImm:
    return lslImm();
  case Instr::lslReg:
    return lslReg();
  case Instr::lsrImm:
    return lsrImm();
  case Instr::rrx:
    return rrx();
  case Instr::rorImm:
    return rorImm();
  case Instr::rorReg:
    return rorReg();
  case Instr::rsbImm:
    return rsbImm();
  case Instr::rsbReg:
    return rsbReg();
  case Instr::rsbShiftedReg:
    return rsbShiftedReg();
  case Instr::rscImm:
    return rscImm();
  case Instr::rscReg:
    return rscReg();
  case Instr::rscShiftedReg:
    return rscShiftedReg();
  case Instr::movImm: // not
    return movImm();
  case Instr::movImm16:
    return movImm16();
  case Instr::movReg:
    return movReg();
  case Instr::movt: // not
    return movt();
  case Instr::bicImm:
    return bicImm();
  case Instr::bicReg:
    return bicReg();
  case Instr::bicShiftedReg:
    return bicShiftedReg();
  case Instr::bfc:
    return bfc();
  case Instr::bfi:
    return bfi();
  case Instr::clz:
    return clz();
  case Instr::mla:
    return mla();
  case Instr::mls:
    return mls();
  case Instr::mrs:
    return mrs();
  case Instr::msrImmApp:
    return msrImmApp();
  case Instr::msrApp:
    return msrApp();
  case Instr::mvnImm: // not
    return mvnImm();
  case Instr::mvnReg:
    return mvnReg();
  case Instr::mvnShiftedReg:
    return mvnShiftedReg();
  case Instr::mul:
    return mul();
  case Instr::nop:
    return nxt();
  case Instr::pkh:
    return pkh();
  case Instr::qadd: //==
    return qadd();
  case Instr::qadd16:
    return qadd16();
  case Instr::qadd8:
    return qadd8();
  case Instr::qasx:
    return qasx();
  case Instr::qdadd:
    return qdadd();
  case Instr::qdsub:
    return qdsub();
  case Instr::qsax:
    return qsax();
  case Instr::qsub:
    return qsub();
  case Instr::qsub16:
    return qsub16();
  case Instr::qsub8:
    return qsub8(); //===
  case Instr::rbit:
    return rbit();
  case Instr::rev:
    return rev();
  case Instr::rev16:
    return rev16();
  case Instr::revsh:
    return revsh();
  case Instr::sbfx:
    return sbfx();
  case Instr::sdiv:
    return sdiv();
  case Instr::ubfx:
    return ubfx();
  case Instr::udiv:
    return udiv(); //=======not
  case Instr::umaal:
    return umaal();
  case Instr::umlal:
    return umlal();
  case Instr::umull:
    return umull();
  case Instr::uxtab:
    return uxtab();
  case Instr::uxtab16:
    return uxtab16();
  case Instr::uxtah:
    return uxtah();
  case Instr::uxtb:
    return uxtb();
  case Instr::uxtb16:
    return uxtb16();
  case Instr::uxth:
    return uxth();
  case Instr::sxtab:
    return sxtab();
  case Instr::sxtab16:
    return sxtab16();
  case Instr::sxtah:
    return sxtah();
  case Instr::sxth:
    return sxth();
  case Instr::sxtb:
    return sxtb();
  case Instr::sxtb16:
    return sxtb16(); // T
  case Instr::smlabb:
    return smlabb();
  case Instr::smlad:
    return smlad();
  case Instr::smlal:
    return smlal();
  case Instr::smlalbb:
    return smlalbb();
  case Instr::smlald:
    return smlald();
  case Instr::smlawb:
    return smlawb();
  case Instr::smlsd:
    return smlsd();
  case Instr::smlsld:
    return smlsld();
  case Instr::smmla:
    return smmla();
  case Instr::smmls:
    return smmls();
  case Instr::smmul:
    return smmul();
  case Instr::smuad:
    return smuad();
  case Instr::smulbb:
    return smulbb();
  case Instr::smull:
    return smull();
  case Instr::smulwb:
    return smulwb();
  case Instr::smusd:
    return smusd();
  case Instr::ssat:
    return ssat();
  case Instr::ssat16:
    return ssat16();
  case Instr::usat:
    return usat();
  case Instr::usat16:
    return usat16();
  case Instr::sadd16:
    return sadd16();
  case Instr::sadd8:
    return sadd8();
  case Instr::sasx:
    return sasx();
  case Instr::sel:
    return sel();
  case Instr::shadd16:
    return shadd16();
  case Instr::shadd8:
    return shadd8();
  case Instr::shasx:
    return shasx();
  case Instr::ssax:
    return ssax();
  case Instr::shsax:
    return shsax();
  case Instr::orrImm:
    return orrImm();
  case Instr::ssub16:
    return ssub16();
  case Instr::ssub8:
    return ssub8();
  case Instr::shsub16:
    return shsub16();
  case Instr::shsub8:
    return shsub8();
  case Instr::usax:
    return usax();
  case Instr::usub16:
    return usub16();
  case Instr::usub8:
    return usub8();
  case Instr::uadd16:
    return uadd16();
  case Instr::uadd8:
    return uadd8();
  case Instr::uasx:
    return uasx();
  case Instr::uhadd16:
    return uhadd16();
  case Instr::uhadd8:
    return uhadd8();
  case Instr::uhasx:
    return uhasx();
  case Instr::uhsax:
    return uhsax();
  case Instr::uhsub16:
    return uhsub16();
  case Instr::uhsub8:
    return uhsub8();
  case Instr::usad8:
    return usad8();
  case Instr::usada8:
    return usada8();
  case Instr::uqadd16:
    return uqadd16();
  case Instr::uqadd8:
    return uqadd8();
  case Instr::uqasx:
    return uqasx();
  case Instr::uqsax:
    return uqsax();
  case Instr::uqsub16:
    return uqsub16();
  case Instr::uqsub8:
    return uqsub8();
  //====== mem ========
  case Instr::strReg:
    return strReg();
  case Instr::ldrReg:
    return ldrReg();
  case Instr::strImm:
    return strImm();
  case Instr::ldrImm:
    return ldrImm();
  case Instr::ldrLit:
    return ldrLit();
  case Instr::ldrbImm:
    return ldrbImm();
  case Instr::strbImm:
    return strbImm();
  case Instr::strbReg:
    return strbReg();
  case Instr::ldrbReg:
    return ldrbReg();
  case Instr::ldrbLit:
    return ldrbLit();
  case Instr::ldrhImm:
    return ldrhImm();
  case Instr::ldrhLit:
    return ldrhLit();
  case Instr::ldrhReg:
    return ldrhReg();
  case Instr::ldrshImm:
    return ldrshImm();
  case Instr::ldrshLit:
    return ldrshLit();
  case Instr::ldrsh:
    return ldrshReg();
  case Instr::ldrsbImm:
    return ldrsbImm();
  case Instr::ldrsbLit:
    return ldrsbLit();
  case Instr::ldrsbReg:
    return ldrsbReg();
  case Instr::ldrdImm:
    return ldrdImm();
  case Instr::ldrdLit:
    return ldrdLit();
  case Instr::ldrdReg:
    return ldrdReg();
  case Instr::ldrex:
    return ldrex();
  case Instr::ldrexb:
    return ldrexb();
  case Instr::ldrexh:
    return ldrexh();
  case Instr::ldrexd:
    return ldrexd();
  case Instr::ldm:
    return ldm();
  case Instr::ldmda:
    return ldmda();
  case Instr::ldmdb:
    return ldmdb();
  case Instr::ldmib:
    return ldmib();
  case Instr::strhImm:
    return strhImm();
  case Instr::strhReg:
    return strhReg();
  case Instr::strdImm:
    return strdImm();
  case Instr::strd:
    return strdReg();
  case Instr::strex:
    return strex();
  case Instr::strexb:
    return strexb();
  case Instr::strexh:
    return strexh();
  case Instr::strexd:
    return strexd();
  case Instr::stm:
    return stm();
  case Instr::stmda:
    return stmda();
  case Instr::stmdb:
    return stmdb();
  case Instr::stmib:
    return stmib();
  case Instr::pop:
    return pop();
  case Instr::push:
    return push();
  //=== branch ====
  case Instr::b:
    return b();
  case Instr::bl:
    return bl();
  case Instr::bx:
    return bx();
  case Instr::wfi:
    printf("==== WFI ====\n");
    exit(0);
  case Instr::wfe:
    printf("==== WFE ====\n");
    exit(0);
  default:
    printf("unhandled instruction: ");
    Decoder::printInstr(instr);
    abort();
  }
}

u32 Cpu::x(const char *prog) { return exec(assemble(prog)); }

void Cpu::test() {
  Cpu c;
  c.r(0, 0xffffffff);
  c.x("str r0, [r1, r4]");
  c.x("str r0, [r1, #4]");
  c.r(0, 0xddddddd8);
  c.x("str r0, [r1, #8]");
  c.r(13, 12);
  c.x("push {r0, r1, r2}");
  c.expectreg(13, 0x0);
  ;
}
